[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/debian"
include_regex = "trixie-\\d{8}-slim"

[TERRARIA]
source = "regex"
regex = "https://terraria.org/api/download/pc-dedicated-server/terraria-server-(\\d\\d\\d\\d).zip"
url = "https://terraria.fandom.com/wiki/Server"
encoding = "utf8"
sort_version_key = "vercmp"

[CONFD]
source = "github"
github = "kelseyhightower/confd"
use_max_tag = true
prefix = "v"
